export const EXAMPLE = 'EXAMPLE';
export const CREATE_CONNECTION = 'CREATE_CONNECTION';
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION';
export const SET_OPONENT_SOCKETID = 'SET_OP_SOCKETID';
export const CLEAR_OPONENT_SOCKETID = 'CLEAR_OP_SOCKETID';

export const CONNECT_DB = 'CONNECT_DB';
export const CLOSE_DB = 'CLOSE_DB';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
